version: '3.1'
services:
  odoo_server:
    image: odoo:16.0
    env_file: .env
    depends_on:
      - odoo_db
    ports:
      - "8069:8069" 
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
  odoo_db:
    image: postgres:13
    env_file: .env
    volumes:
      - db:/var/lib/pgsql/data/pgdata
    ports:
      - "5433:5432"
volumes:
  data:
  db:
