from . import (
    hr_custom_department, 
    hr_department_tipo_unidad,
    hr_custom_employee,
    hr_employee_marital, 
    hr_employee_nro_legajo, 
    hr_employee_situacion_revista_1, 
    hr_employee_situacion_revista_2,
    hr_employee_grupo_familiar,
    hr_employee_formacion,
    hr_employee_cuil,
    hr_employee_puestos,
    hr_employee_titulo_carrera,
    hr_employee_entidad_otorgante,
    hr_employee_area,
    hr_employee_cargo,
    hr_employee_obra_social,
    )
